apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ywui6ycho-nodejs
  janus-idp.io/tekton: ywui6ycho-nodejs
  backstage.io/kubernetes-id: ywui6ycho-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ywui6ycho-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
